# Commands

# kubectl create secret tls caashieresecret --cert=path/to/secret.cert --key=path/to/secret.key

apiVersion: v1
kind: Secret
metadata:
  name: caashieresecret
type: kubernetes.io/tls
data:
  tls.crt: <base64 encoded certificate>
  tls.key: <base64 encoded private key>