# Commands

# kubectl get rs

# kubectl delete rs kuard --cascade=false (Keeping the pods)

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nunu-replica
  labels:
    application: nunu
    version: v1.0.0
    environment: development
spec:
  replicas: 2
  selector:
    matchLabels:
      application: nunu
  template:
    metadata:
      labels:
        application: nunu
        version: v1.0.0
        environment: development
      annotations:
        url: "nunu.caashiere"
    spec:
      containers:
      - name: nunu
        image: caashiere/nunu:latest
        ports:
          - containerPort: 2406
            name: portnunu
            protocol: TCP
        resources:
          requests:
            cpu: "500m" # 0.5 CPU
            memory: "128Mi" # 128 MB
          limits:
            cpu: "1000m" # 1.0 CPU
            memory: "256Mi" # 256 MB
        readinessProbe:
          httpGet:
            path: /ready
            port: 2406
          initialDelaySeconds: 0
          failureThreshold: 3
          successThreshold: 1
          periodSeconds: 2
        livenessProbe:
          httpGet:
            path: /health
            port: 2406
          initialDelaySeconds: 5
          failureThreshold: 3
          timeoutSeconds: 1
          periodSeconds: 10