# COMMANDS

# kubectl get hpa

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: olivia-deployment-hscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: olivia-deployment
  minReplicas: 3
  maxReplicas: 9
  targetCPUUtilizationPercentage: 80